plugins {
    alias libs.plugins.fabric.loom
    id 'maven-publish'
}

version = libs.versions.mod.get()
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    mods {
        "fabric-modlister" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
}

dependencies {
    minecraft libs.minecraft
    implementation libs.fabric.loader

}

processResources {
    def minecraftRuntimeVersion = libs.versions.minecraft.runtime.get()
    def loaderVersion = libs.versions.fabric.loader.get()
    def javaVersion = libs.versions.java.get()
    def mixinVersion = libs.versions.mixin.get()
    inputs.property "version", project.version
    inputs.property "minecraft_version", minecraftRuntimeVersion
    inputs.property "loader_version", loaderVersion
    inputs.property "java_version", javaVersion
    inputs.property "mixin_version", mixinVersion
    filteringCharset "UTF-8"

    filesMatching(["fabric.mod.json", "fabric-modlister.mixins.json"]) {
        expand "version": project.version,
                "minecraft_version": minecraftRuntimeVersion,
                "loader_version": loaderVersion,
                "java_version": javaVersion,
                "mixin_version": mixinVersion
    }
}

def targetJavaVersion = libs.versions.java.get().toInteger()
tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release.set(targetJavaVersion)
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

tasks.register("copyModJar", Sync) {
    dependsOn tasks.named("jar")
    from tasks.named("jar").flatMap { it.archiveFile }
    into layout.projectDirectory.dir("target")
}

tasks.named("build") {
    dependsOn tasks.named("copyModJar")
}

// configure the maven publication
publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
