[versions]
loom = "1.17-SNAPSHOT"
minecraft = "26.3-SNAPSHOT-9"
minecraft-runtime = "26.3-SNAPSHOT-9"
fabric-loader = "0.19.3"
mod = "1.0.9-SNAPSHOT"
java = "25"
mixin = "0.8"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
