[versions]
loom = "1.18+"
minecraft = "26.4-snapshot-2" #snapshot-X
minecraft-runtime = "26.4-alpha.2" #use Alpha.X
fabric-loader = "0.19.5"
mod = "1.0.264"
java = "25"
mixin = "0.8"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
